# Generated by Django 5.0.6 on 2024-06-17 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('ISO3166_2', models.CharField(blank=True, max_length=10, null=True)),
                ('distance_nearest_bank', models.FloatField(blank=True, null=True)),
                ('distance_nearest_fuel', models.FloatField(blank=True, null=True)),
                ('distance_nearest_office', models.FloatField(blank=True, null=True)),
                ('distance_nearest_police', models.FloatField(blank=True, null=True)),
                ('distance_nearest_townhall', models.FloatField(blank=True, null=True)),
                ('distance_nearest_bus_station', models.FloatField(blank=True, null=True)),
                ('distance_nearest_bus_stop', models.FloatField(blank=True, null=True)),
                ('distance_nearest_convenience', models.FloatField(blank=True, null=True)),
                ('distance_nearest_mall', models.FloatField(blank=True, null=True)),
                ('distance_nearest_supermarket', models.FloatField(blank=True, null=True)),
                ('distance_nearest_books', models.FloatField(blank=True, null=True)),
                ('distance_nearest_coffee', models.FloatField(blank=True, null=True)),
                ('distance_nearest_department_store', models.FloatField(blank=True, null=True)),
                ('distance_nearest_clothes', models.FloatField(blank=True, null=True)),
                ('distance_nearest_bakery', models.FloatField(blank=True, null=True)),
                ('distance_nearest_cafe', models.FloatField(blank=True, null=True)),
                ('count_bank_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_fuel_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_office_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_police_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_townhall_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_bus_station_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_bus_stop_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_convenience_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_mall_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_supermarket_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_books_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_coffee_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_department_store_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_clothes_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_bakery_within_500m', models.IntegerField(blank=True, null=True)),
                ('count_cafe_within_500m', models.IntegerField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
