# Generated by Django 5.0.6 on 2024-06-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_userlocation_predicted_amenity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='count_apartment_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_artwork_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_atm_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_attraction_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_camp_site_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_chalet_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_clinic_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_crossing_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_fast_food_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_guest_house_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_hospital_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_hotel_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_information_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_motel_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_motorway_junction_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_museum_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_pharmacy_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_picnic_site_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_restaurant_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_school_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_station_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_traffic_signals_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_viewpoint_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_village_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_waterfall_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_wilderness_hut_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='count_zoo_within_500m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_apartment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_artwork',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_atm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_attraction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_camp_site',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_chalet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_clinic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_crossing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_fast_food',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_guest_house',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_hospital',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_hotel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_information',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_motel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_motorway_junction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_museum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_pharmacy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_picnic_site',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_restaurant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_school',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_station',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_traffic_signals',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_viewpoint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_village',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_waterfall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_wilderness_hut',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='distance_nearest_zoo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
