# Generated by Django 5.0.6 on 2024-09-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_businessownercount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
                ('value', models.FloatField()),
            ],
        ),
    ]
