# Generated by Django 5.0.6 on 2024-09-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_closedbusinesscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
