# Generated by Django 4.2.13 on 2024-10-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_delete_locationcategory_remove_location_iso3166_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
