# Generated by Django 5.0.6 on 2024-06-07 13:10

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_onetimepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[accounts.validators.validate_email_address], verbose_name='Email Address'),
        ),
    ]
