# Generated by Django 4.2.13 on 2024-07-22 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 12, 34, 1, 201742, tzinfo=datetime.timezone.utc)),
        ),
    ]
