# Generated by Django 4.2.13 on 2024-08-18 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_onetimepassword_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 16, 24, 36, 416180, tzinfo=datetime.timezone.utc)),
        ),
    ]
