# Generated by Django 4.2.13 on 2024-09-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_onetimepassword_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='last_resent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
